# Generated by Django 3.2.8 on 2021-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('image', models.ImageField(upload_to='home/news/', verbose_name='Imagen')),
                ('paragraph1', models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 1')),
                ('paragraph2', models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 2')),
                ('paragraph3', models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 3')),
                ('paragraph4', models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 4')),
                ('paragraph5', models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 5')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Dirección Web')),
                ('fichero', models.FileField(blank=True, null=True, upload_to='home/videos/', verbose_name='Fichero')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created'],
            },
        ),
    ]
