# Generated by Django 3.2.8 on 2021-10-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Dirección Web'),
        ),
    ]
