# Generated by Django 3.2.8 on 2021-10-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_videos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Dirección Web'),
        ),
    ]
