# Generated by Django 3.2.8 on 2021-10-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_videos_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='paragraph',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Parrafo'),
        ),
    ]
