# Generated by Django 3.2.8 on 2021-10-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_news_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 3'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph4',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 4'),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph5',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Parrafo 5'),
        ),
    ]
