# Generated by Django 3.2.8 on 2021-11-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211025_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
